chore(gatsby-plugin-sharp, gatsby-transformer-sharp): update dependencies
gatsbyjs/gatsby pull request #26259
Opened 2020-08-06 04:23 UTC by hoobdeebla

## Description

Updates dependencies of `gatsby-plugin-sharp` and `gatsby-transformer-sharp` to the latest Node 10.13-compatible versions. [`got`](/sindresorhus/got) was updated to version 10 as `got@11` is incompatible with Node <10.19.

### Documentation

Respective packages' READMEs (unchanged)

## Related Issues

None

2020-08-19 18:34 UTC, hoobdeebla commented
@wardpeet, anything I can do to help get this merged?

2020-08-27 06:03 UTC, hoobdeebla commented
Hello @wardpeet, I would very much appreciate a review.

2020-08-27 07:47 UTC, wardpeet commented
Sorry @hoobdeebla, i'll be checking it out as we speak :)

2020-08-27 12:18 UTC, wardpeet requested changes
1 small remark :) looks good! thanks for taking the time

2020-08-27 12:18 UTC, wardpeet commented on packages/gatsby-plugin-sharp/src/scheduler.js
> +const fs = require(`fs`)
Please keep fs-extra as it has better windows support.
```suggestion
const fs = require(`fs-extra`)
```

2020-08-27 16:16 UTC, hoobdeebla commented
All fixed, all green. Thank you for the review!

2020-08-28 18:35 UTC, wardpeet approved these changes
LGTM! thanks for fixing and upgrading

2020-08-28 18:35 UTC, merged