chore(gatsby): Migrate types/node-interface.js to TypeScript
gatsbyjs/gatsby pull request #26733
Opened 2020-09-01 08:30 UTC by alisson-suzigan

### Description
This PR converts the file packages/gatsby/src/schema/types/node-interface.js to TS:

### Related Issue
Related to #21995

2020-09-08 22:14 UTC, alisson-suzigan commented
Hi folks.
Does this PR still make sense?

2020-09-15 10:08 UTC, alisson-suzigan commented
Hello, is anyone there?

2020-09-15 12:49 UTC, vladar requested changes
Thanks for suggesting this 👍 

In general it looks good to me but there are two incorrect types which I mention in inline comments. Fix those and we are good to go!

2020-09-15 12:49 UTC, vladar commented on packages/gatsby/src/schema/types/node-interface.ts
> +        resolve: (source, _args, context): Node => {
```suggestion
        resolve: (source, _args, context): Node | null => {
```

2020-09-15 12:49 UTC, vladar commented on packages/gatsby/src/schema/types/node-interface.ts
> +        resolve: (source, _args, context): Node => {
```suggestion
        resolve: (source, _args, context): Array<Node> => {
```

2020-09-17 08:13 UTC, alisson-suzigan commented
@vladar, the code was changed following your suggestion. Thanks.

2020-09-17 10:11 UTC, vladar approved these changes
Awesome, thanks! 💜

2020-09-17 10:12 UTC, merged