Remove extra white spaces from generated excerpt in gatsby-plugin-mdx
gatsbyjs/gatsby pull request #26796
Opened 2020-09-06 03:24 UTC by emgoto

## Description
When an MDX file includes a link that would be shown in the plaintext excerpt, an extra space is added after the link.

## Related Issues
Same problem as #12398 which was fixed in #12878.

Fixes #16035.

2020-09-08 09:18 UTC, pvdz requested changes
Please remove the `const` to `let` change. I don't see a reason for it.

2020-09-08 09:18 UTC, pvdz commented on packages/gatsby-plugin-mdx/gatsby/source-nodes.js
> +          let excerptNodes = []
Why did you change this? I guess you literally copy/pasted the changes from the other PR? Please undo this line.

2020-09-08 09:18 UTC, pvdz commented on packages/gatsby-plugin-mdx/gatsby/source-nodes.js
> +              excerptNodes.push(node.alt)
I've updated the title of the PR to match this change.

2020-09-08 09:22 UTC, pvdz commented on packages/gatsby-plugin-mdx/gatsby/source-nodes.js
> +          let excerptNodes = []
(I've reverted this change from the other PR as well)

2022-07-26 08:10 UTC, LekoArts commented
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

Unfortunately we won't merge this PR at the moment because MDX v2 is on the horizon: https://github.com/gatsbyjs/gatsby/discussions/25068

We completely focus on MDX v2 at the moment and won't focus on the old version of `gatsby-plugin-mdx` anymore.

Please try that out and if this still occurs there, comment on the discussion. Thanks!

2022-07-26 08:10 UTC, closed without merging