feat(gatsby-telemetry): create telemetry service
gatsbyjs/gatsby pull request #26832
Opened 2020-09-09 09:15 UTC by mxstbr

As we noticed in #26627, gatsby-telemetry can only run in a node context. In order to add telemetry to Admin we need to create a HTTP server that exposes the telemetry methods for Admin to POST to.

- [x] Set up express server
- [x] Expose basic `setGatsbyCliVersion` and `setDefaultComponentId`
- [ ] Figure out whether to add this to the service discovery or not
- [ ] Expose all necessary methods that Admin needs

2020-09-09 10:14 UTC, jamo approved these changes
🤩

2020-09-09 11:03 UTC, wardpeet requested changes
Can we make this part of gatsby-admin and not part of telemetry?

2020-09-09 12:30 UTC, mxstbr commented
> Can we make this part of gatsby-admin and not part of telemetry?
> Why did you add it to telemetry and not admin itself?

I put it in `gatsby-telemetry` because there is nothing Admin-specific in that HTTP server. There will be Admin-specific bits, specifically starting this as a discoverable service for each site, however those will likely have to live in `gatsby develop`.

I'd be happy to physically move that file to `gatsby-admin` if you'd prefer that!

2020-09-09 12:50 UTC, wardpeet commented
My mistake, please move it to `gatsby-develop` not gatsby-admin 👍. I just don't want it living in gatsby-telemetry.

2020-09-10 14:08 UTC, mxstbr commented
Done! Ready for a re-review @wardpeet 👍

2020-09-14 08:16 UTC, wardpeet approved these changes
Seems to work :) Looking good

2020-09-14 08:23 UTC, merged