Update analytics.md with gatsby-plugin-gtag
gatsbyjs/gatsby pull request #27081
Opened 2020-09-26 04:43 UTC by 98lenvi

## Description

- Adds `gatsby-plugin-gtag` description to `analytics.md`
- Informs user on why `gtag.js` is more preferable than using `analytics.js`

## Related Issues

Fixes #27065

2020-10-02 17:37 UTC, meganesu requested changes
Hi @98lenvi, thanks for submitting this PR! I've left a few comments with suggestions for improvements, but other than that I think this looks good.

Thanks for your contribution! 💜

2020-10-02 17:37 UTC, meganesu commented on docs/docs/adding-analytics.md
> +We are going to use `gatsby-plugin-gtag`.
I think it makes sense to leave the second sentence, so readers can easily jump to the list of other options.

```suggestion
We are going to use `gatsby-plugin-gtag`. For other analytics options (including Google Tag Manager), check [other Gatsby analytics plugins](#other-gatsby-analytics-plugins).
```

2020-10-02 17:37 UTC, meganesu commented on docs/docs/adding-analytics.md
> +npm install --save gatsby-plugin-gtag
You don't need the `--save` flag here (the plugin docs should probably also be updated, but that's a separate issue).

```suggestion
npm install gatsby-plugin-gtag
```

2020-10-02 17:37 UTC, meganesu commented on docs/docs/adding-analytics.md
> +        // your google analytics tracking id
Trying to clarify further.

```suggestion
        // replace `UA-XXXXXXXXX-X` with your own Google Analytics Tracking ID
```

2020-10-03 09:09 UTC, 98lenvi commented
@meganesu, Hi! Thanks for the review. I've made the changes. Please check it now 😄

2020-10-06 21:02 UTC, meganesu approved these changes
Looks great! ✨

Thanks for your contribution! 💜

2020-10-06 21:02 UTC, merged

2020-10-21 03:35 UTC, pfortes commented
Hello, is there a reason you are using gatsby-plugin-gtag instead of gatsby-plugin-google-gtag which seams to be the oficial one, has more installs and better docs?

thank you

2020-10-23 18:24 UTC, meganesu commented
@pfortes Oops, you're right. That's my fault. When I was writing up the initial issue, I pulled the first search result from the plugin library without realizing we had an official one. Thanks for pointing that out! 💜

I've opened a new issue for updating the doc to use the official `gatsby-plugin-google-gtag` plugin. If you're interested in making the update, feel free to comment on it and I can assign it to you.

2020-10-23 19:21 UTC, pfortes commented
@meganesu Great, thanks for confirming this.
I will be happy to make the update, will comment on the issue.

Have a great day!