fixing by remove/change the word simply and easily in many documentation
gatsbyjs/gatsby pull request #27217
Opened 2020-10-01 18:33 UTC by dennisgon

## Description

I Removed or change the word "just" and "simply" from the sentence following for issue #18702 to appear more interactive and formal.

### Documentation

## Related Issues
Addresses  #18702

2020-10-01 20:31 UTC, pvdz requested changes
Okay I'm stopping at five suggestions.

Thanks for your PR but this needs more work. Please don't just eliminate the words but consider what the end result looks like.

I'm not a native English speaker and also won't be the final person reviewing this PR, but it is clear to me that this PR cannot be merged as is. Please go through your changes more closely and consider whether or not they in fact meet the requirement of the original issue, and if so, how to properly rewrite them. Sometimes it is sufficient to just drop the word but often it will require rephrasing the sentence to make it "right".

Please don't make us spend more time on this than it would take to do the change ourselves.

Thank you.

2020-10-01 20:31 UTC, pvdz commented on docs/docs/answering-it-security.md
> +- Gatsby adds a layer of indirection which obscures your CMS -- so even if your CMS _is_ vulnerable, bad actors have no idea where to find it. This is in contrast to systems where bad actors can be l
I think this is not an example of the issue outlined in the linked issue.

Additionally, I'm certain the change is incorrect.

2020-10-01 20:31 UTC, pvdz commented on docs/docs/css-in-js.md
> +CSS-in-JS refers to an approach where styles are written in JavaScript instead of in external CSS files to scope styles in components, eliminate dead code, encourage faster performance and dynamic st
I would rephrase this, "to make it easier to scope styles in components", for example.

2020-10-01 20:31 UTC, pvdz commented on docs/docs/debugging.md
> +While building your site, you’ll sometimes encounter bugs. These guides help you set up debugging in Gatsby so you can spot and squash bugs more.
While the occurrence may be valid (not completely sure), removing the word like this leaves an awkward sentence at best, if not actually an incorrect sentence. Something like "so it makes it easier for you to spot bugs", or something in that line.

2020-10-01 20:31 UTC, pvdz commented on docs/docs/deploying-to-netlify.md
> +platform that automates your code to create performant, More easier maintainable
Capitalization error. I think in this case you can omit the word without further replacement.

2020-10-01 20:31 UTC, pvdz commented on docs/docs/gatsby-for-companies.md
> +If you work in this organization, and want your organization to use Gatsby more, you can go by [getting other developers excited by Gatsby](/docs/winning-over-developers/).
The resulting phrase is awkward. I don't think this is correct.

2020-10-02 03:58 UTC, dennisgon commented
Ok I will fix it

2020-10-02 09:23 UTC, pvdz requested changes
Hey, thanks but I don't think this is enough.

Can you please do a `grep -r 'easily' docs/` and `grep -r 'just' docs/` and resolve the issue entirely? Please take care in considering whether or not an occurrence of `easily` or `just` is in fact covered by the issue, or maybe rather a different meaning (like the temporal case outlined in my comment below).

I'd like to see a PR that closes the referenced issue so we can close it. At least for the occurrences of `easily` and `just`. Otherwise we will have to spend even more time going through hundreds of individual PRs and that will take us more time than doing it ourselves.

Thank you :purple_heart:

2020-10-02 18:11 UTC, dennisgon commented
Thanks,
I find another word that i already fix it

2020-10-02 18:16 UTC, pvdz commented
@dennisgon I'm going to be brutally honest here; I don't think we're going to merge this PR. Just glancing through it I already see a bunch of grammatical problems and you even left a merge conflict in there. As such I'm going to close it.

My guess is that you're participating in Hacktober. That's great! Is there any chance you could find a code change you'd like to submit, rather than a docs change?

2020-10-02 18:16 UTC, closed without merging