Make optional SVG favicon come after the fallback
gatsbyjs/gatsby pull request #27566
Opened 2020-10-20 11:27 UTC by ciromattia

Fixes #26083 Chrome choosing the favicon which comes last.

## Description

### Documentation

## Related Issues

2020-10-20 14:39 UTC, moonmeister commented
Thanks!  You'll probably need to update test snapshots to get tests to pass

2020-10-21 09:11 UTC, ciromattia commented
> Thanks! You'll probably need to update test snapshots to get tests to pass

uh, I edited directly from github, let me look at the whole contributing process :)

2020-10-21 14:17 UTC, moonmeister commented
no worries if not, I'll have time in a couple days to finish it.

2020-11-05 00:05 UTC, trevorblades requested changes
@moonmeister @ciromattia one possible reason for the tests not passing is mixed up brackets/parens in the code. I commented on the two lines in question, but here's a full example of what the implementation should be:

```js
if (srcIconExists) {
  if (insertFaviconLinkTag) {
    favicons.forEach(favicon => {
      headComponents.push(
        <link
          key={`gatsby-plugin-manifest-icon-link-png`}
          rel="icon"
          href={withPrefix(
            addDigestToPath(favicon.src, cacheDigest, cacheBusting)
          )}
          type="image/png"
        />
      )
    })
    if (icon?.endsWith(`.svg`)) {
      headComponents.push(
        <link
          key={`gatsby-plugin-manifest-icon-link-svg`}
          rel="icon"
          href={withPrefix(
            addDigestToPath(`favicon.svg`, cacheDigest, cacheBusting)
          )}
          type="image/svg+xml"
        />
      )
    }
  }
}
```

2020-11-05 00:05 UTC, trevorblades commented on packages/gatsby-plugin-manifest/src/gatsby-ssr.js
>        })
This should just be a `}`

2020-11-05 00:05 UTC, trevorblades commented on packages/gatsby-plugin-manifest/src/gatsby-ssr.js
>        }
This should be `})`, like the line of the other comment

2020-11-05 00:11 UTC, trevorblades commented
I've made these changes and PR'd them to @ciromattia's branch. They should be able to be merged in and hopefully tests will pass then :)

We may still need to update snapshots since the order of `<link>`s changed, but I'll look into that now.

2020-11-05 00:18 UTC, moonmeister commented
> I've made these changes and [PR'd them](https://github.com/ciromattia/gatsby/pull/1) to @ciromattia's branch. They should be able to be merged in and hopefully tests will pass then 😄 
> 
> We may still need to update snapshots since the order of `<link>`s changed, but I'll look into that now.

You're a gem. Thanks for doing this, I've been to busy for oss work.

2020-11-05 00:28 UTC, trevorblades commented
No problem! I just ran tests and tried to update snapshots, but I guess none of them needed to be updated after all. I just opened https://github.com/gatsbyjs/gatsby/pull/27843 (the branch I was PR'ing into this branch) to see if I could get the tests to pass there. I suppose if they do, merging that PR would be the same thing as merging my PR into this branch, and then this branch into gatsby/master.

2020-11-05 00:34 UTC, moonmeister commented
Yeah, no need to make more work, if that passes I'll close this in favor of the other.

2020-11-07 00:43 UTC, moonmeister commented
closing in favor of #27843

2020-11-07 00:43 UTC, closed without merging