chore(docs): fix broken url
gatsbyjs/gatsby pull request #28197
Opened 2020-11-20 02:50 UTC by saintmalik

## Summary

Easy navigation and easy reading for others.

2020-11-20 14:02 UTC, vladar requested changes
Thank you for opening a PR. I've posted a comment below.

2020-11-20 14:02 UTC, vladar commented on packages/gatsby-plugin-react-helmet/README.md
> +- [GatsbyJS.org](https://github.com/gatsbyjs/gatsby/blob/pieh-www-tests-master/www/src/components/site-metadata.js)
I think we should just remove `gatsby.org` example for now. We can replace it with something else. Let's use `kentcdodds.com`:

```suggestion
- [kentcdodds.com](https://github.com/kentcdodds/kentcdodds.com/blob/master/src/components/seo/index.js)
```

2020-11-24 14:00 UTC, saintmalik commented
> Thank you for opening a PR. I've posted a comment below.

Made the fix already

2020-11-27 09:41 UTC, LekoArts approved these changes

2020-11-27 09:41 UTC, merged