fix(gatsby): invalidate queries if page context changes between runs
gatsbyjs/gatsby pull request #28351
Opened 2020-11-29 15:43 UTC by pieh

This is successor to https://github.com/gatsbyjs/gatsby/pull/28316 which had potential of causing OOM crashes when persisting/serializing data in case there was huge amount of data passed via page context.

Instead of persisting entire page objects this persists just hash generated from page context which should minimize how much more data will be persisted (and hopefully avoid OOM crashes)

TODO:
 - [ ] determine if https://github.com/gatsbyjs/gatsby/blob/c4978e948c5b0cebf85ef9af62da523169994bf9/packages/gatsby/src/services/create-pages.ts#L57 needs to be adjusted - right now it uses `pages` slice which is not persisted - so it's entirely possible that this will keep stale page context hashes around. Potential solution here would be to add timestamp to newly added reducer (maybe even just move current ones we have in `pages` to new one) and switch to using new (persisted) slice of redux state for finding pages that were not re-created.

## Related Issues

fixes #28281
fixes #26520

2020-11-30 09:34 UTC, vladar approved these changes
Looks good to me 👍 At least I don't see any pitfalls with this approach.

2020-11-30 09:34 UTC, vladar commented on packages/gatsby/src/query/__tests__/data-tracking.js
> +  describe(`Changing page context invalidates page queries`, () => {
🎉

2020-12-02 14:52 UTC, pieh commented
Ok, this is not sufficent change. As I noted in the description

> determine if https://github.com/gatsbyjs/gatsby/blob/c4978e948c5b0cebf85ef9af62da523169994bf9/packages/gatsby/src/services/create-pages.ts#L57 needs to be adjusted - right now it uses `pages` slice which is not persisted - so it's entirely possible that this will keep stale page context hashes around. Potential solution here would be to add timestamp to newly added reducer (maybe even just move current ones we have in `pages` to new one) and switch to using new (persisted) slice of redux state for finding pages that were not re-created.

Just did run some manual tests for it. For cases when we:
 - run build #1 that creates "page A",
 - run build #2 without "page A",
 - run build #3 with "page A" re-added
we don't rerun query in "build #3" and "build #2" deletes generated files - most importantly `page-data` ( to not show page that was "deleted")

This result in build error as follows:
```
failed Building static HTML for pages - 0.757s
 ERROR #95313 
Building static HTML failed for path "/context/b/"
See our docs page for more info on this error: https://gatsby.dev/debug-html
  Error: ENOENT: no such file or directory, open '/Users/misiek/dev/gatsby-starter-blog/public/page-data/context/b/page-data.json'
  - render-page.js:635 getPageData
    /Users/misiek/dev/gatsby-starter-blog/public/render-page.js:635:1022
  - render-page.js:640 Module../.cache/static-entry.js.__webpack_exports__.default
    /Users/misiek/dev/gatsby-starter-blog/public/render-page.js:640:1497
  - render-html.js:30 
    [gatsby-starter-blog]/[gatsby]/dist/utils/worker/render-html.js:30:36
```

So we do need to cover properly cleaning up reducer that we will persist

2020-12-02 14:56 UTC, vladar requested changes
Just trying to discard my review after @pieh request

2020-12-02 16:23 UTC, pieh commented
To add to my above comment - just adding `timestamp` and rest of fields that are used in `findChangedPages` / `deleteUnotuchedPages` doesn't seem sufficient, because after finding deleted pages we do emit `DELETE_PAGE` action which currently uses entire page object as payload. We can adjust internals to make sure things are fine. But various plugins might already subscribe to this event in some cases and while this technically wouldn't be breaking change, it could cause unforseen consequences for the ecosystem...

2020-12-13 10:13 UTC, pieh commented
Ok, this is not feasible approach in the end due to above - I will actually use https://github.com/gatsbyjs/gatsby/pull/28316 as a base and handle potential OOM issues by expanding persisting chunking to also chunk `pages` on top of `nodes` - https://github.com/gatsbyjs/gatsby/pull/28590

Will be closing this PR

2020-12-13 10:13 UTC, closed without merging