fix(gatsby-plugin-sharp): decode URL so it matches the cache key
gatsbyjs/gatsby pull request #28449
Opened 2020-12-02 21:41 UTC by KyleAMathews

Found this on my blog. Also reported in the umbrella issue https://github.com/gatsbyjs/gatsby/discussions/27603#discussioncomment-139695

2020-12-03 07:38 UTC, pvdz requested changes
Can we have a test case that tests a url that doesn't need this (should already be there, I hope?) and a url that does need it?

2020-12-03 10:08 UTC, vladar approved these changes
@pvdz We don't have tests for this experiment yet. But I took over this feature and will be working on adding tests in separate PRs.

This PR is good to go as-is (as for me).

2020-12-03 11:38 UTC, ascorbic approved these changes

2020-12-03 15:10 UTC, merged

2020-12-07 19:28 UTC, pieh commented
Published `gatsby-plugin-sharp@2.10.1`