docs(gatsby-plugin-image): Warn about `styled(StaticImage)` usage
gatsbyjs/gatsby pull request #30345
Opened 2021-03-19 10:21 UTC by ascorbic

The `StaticImage` component doesn't work with higher-order components like the `styled` function from styled-components or Emotion. This explains how you should use the css prop instead.

2021-03-19 14:28 UTC, laurieontech requested changes
I might remove the emojis from the comments in the code snippets. Just seems like an unnecessary addition that may cause weirdness on certain devices. Otherwise looks good.

2021-03-19 14:31 UTC, ascorbic commented
Spoilsport 😛

2021-03-19 14:34 UTC, KyleAMathews commented
Perhaps add a bit of the why? People will be curious and it'll help them better understand other differences of the component vs normal img.

2021-03-19 14:36 UTC, laurieontech reviewed
I'm not approving this just because you're being mean to me :P

2021-03-23 16:45 UTC, laurieontech approved these changes
Well I suppose :P

2021-03-25 11:46 UTC, merged