fix(gatsby): infer shape of warning object
gatsbyjs/gatsby pull request #31489
Opened 2021-05-19 20:12 UTC by KyleAMathews

Different parts of webpack seem to be emitting warnings in different shapes. They were all strings it seems in v4 and then [became objects in webpack 5](https://github.com/gatsbyjs/gatsby/issues/30780) but only mostly? Not really sure. But
this PR tries to just infer the different shapes warnings can come in and handle them.

fixes https://github.com/gatsbyjs/gatsby/issues/31474

2021-05-21 18:37 UTC, vladar requested changes
I think we need to account for a case when the `warnings` array is empty.

2021-05-21 18:37 UTC, vladar commented on packages/gatsby/src/utils/webpack-error-utils.ts
> +  } else if (warnings[0].message && warnings[0].moduleName) {
```suggestion
  } else if (warnings[0]?.message && warnings[0]?.moduleName) {
```

2021-05-21 18:37 UTC, vladar commented on packages/gatsby/src/utils/webpack-error-utils.ts
> +  } else if (warnings[0].message) {
```suggestion
  } else if (warnings[0]?.message) {
```

2021-06-14 07:21 UTC, LekoArts approved these changes

2021-06-14 07:22 UTC, merged