add redux location and interaction examples
gatsbyjs/gatsby pull request #31928
Opened 2021-06-15 16:30 UTC by graysonhicks

These are two examples of working with Gatsby + Redux that will go along with a WIP blog post.

2021-06-17 05:35 UTC, LekoArts requested changes
Thanks! Added some comments

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-interaction-code-splitting/gatsby-browser.js
> +export { default as wrapRootElement } from "./src/redux/reduxWrapper"
To have proper hot reloading you'll want to call the `wrapRootElement` api and use a component that is in PascalCase (Fast Refresh doesn't like lowercased components).

See https://github.com/system-ui/theme-ui/blob/develop/examples/gatsby/gatsby-browser.js for an example

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-interaction-code-splitting/gatsby-ssr.js
> +export { default as wrapRootElement } from "./src/redux/reduxWrapper"
Same as `gatsby-browser.js` comment above

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-interaction-code-splitting/package.json
> +    "gatsby-image": "^3.0.0",
Here are some unused packages in the package.json. image, offline, source-filesystem are all not used

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-interaction-code-splitting/src/redux/reduxWrapper.js
> +export default ({ element }) => (
Anonymous functions are bad practice

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-page-code-splitting/gatsby-node.js
> +// You can delete this file if you're not using it
Delete empty files

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-page-code-splitting/package.json
> +    "gatsby-image": "^2.5.0",
Some unused packages in here

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-page-code-splitting/src/redux/reducers/darkMode.js
> +export default (state = initialState, action) => {
Anonymous function

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-page-code-splitting/src/redux/reducers/dummy.js
> +export default (state = initialState, action) => {
Anonymous function

2021-06-17 05:35 UTC, LekoArts commented on examples/using-redux-w-page-code-splitting/src/redux/reduxWrapper.js
> +export default ({ element }) => (
Anonymous function

2021-06-22 14:42 UTC, graysonhicks commented
Thanks @LekoArts !  Those issues should all be resolved now.

2021-06-23 06:57 UTC, LekoArts approved these changes

2021-06-23 06:57 UTC, merged