Faeture/google oauth functions example
gatsbyjs/gatsby pull request #31953
Opened 2021-06-16 22:11 UTC by graysonhicks

This creates an example for logging in and out with Google OAuth and Gatsby Functions.  It also renames an existing 'google-auth' example to 'google-gmail' to be more accurate in the difference between the two.

This example will compliment a blog post that is in review.

2021-06-17 05:45 UTC, LekoArts requested changes
Thanks!

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-gmail/README.md
> +    cd google-gmail
But that's not the name of the directory? If we want to be super correct it has to be `cd examples/functions-google-gmail`

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/README.md
> +    To get started, run `yarn` to add all necessary packages.
Unfortunately the already merged examples used `yarn` in their examples. This should be fixed in a follow-up.

For this PR we can do it right before the merge. So any instance of `yarn` should be replaced with `npm`

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/README.md
> +    cd functions-google-oauth
Same comment as in other example above

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/gatsby-config.js
> +  // Only need for < 3.7.0 Gatsby
Let's remove it, the example supports it so no need to add it here

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/gatsby-config.js
> +      resolve: `gatsby-plugin-create-client-paths`,
We shouldn't use this plugin and rather use the File System Route API

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/src/api/googleAccessToken.js
> +export default async (req, res) => {
Anonymous functions are bad practice (e.g. for debugging)

2021-06-17 05:45 UTC, LekoArts commented on examples/functions-google-oauth/src/api/login.js
> +export default async (req, res) => {
anonymous

2021-06-22 17:34 UTC, graysonhicks commented
Thanks @LekoArts these should be resolved now!

2021-06-23 06:52 UTC, LekoArts approved these changes

2021-06-23 06:53 UTC, merged