Deprecate createTypes in sourceNodes
gatsbyjs/gatsby pull request #32291
Opened 2021-07-07 20:48 UTC by abhiaiyer91

## Description

### Documentation

## Related Issues

2021-07-08 12:51 UTC, vladar requested changes
I've realized that we need this change for other schema-related actions as well:

`createFieldExtension` and `addThirdPartySchema` should also be updated. And likely there are some test snapshots that must be updated as well.

2021-07-12 17:35 UTC, abhiaiyer91 commented
@vladar updated a test and regenerated snapshots. What do I do about Peril?

2021-07-12 17:36 UTC, abhiaiyer91 commented
Also looks like the snapshot incorrectly updated a worker test. @LekoArts something i did wrong?

2021-07-13 06:54 UTC, LekoArts commented
Peril is sometimes acting weird, we can ignore that. The snapshot change in the worker I'm not sure about myself, I just reverted it and let's see if it passes. It shouldn't have changed anything there.

2021-07-13 11:27 UTC, LekoArts commented
This is btw how it will look like then:

![image](https://user-images.githubusercontent.com/16143594/125444149-180be8d2-9ae6-41aa-9189-6073c00409de.png)

2021-08-19 15:23 UTC, wardpeet approved these changes

2021-09-10 13:48 UTC, merged