feat(gatsby-source-mongodb): Add option name to overwrite node middle…
gatsbyjs/gatsby pull request #33820
Opened 2021-11-02 15:10 UTC by michael-proulx

# gatsby-source-mongodb

Adding optional name to overwrite node middle name.

ex: 
```
options: {
  ...,
  dbName: `cloud`,
  name: `other`,
  collection: `documents`
}

// mongodbOtherDocuments instead of mongodbCloudDocuments
```

## Description

Why implementing this? Dev may have different database name than staging and prod, having this will add the possibility to statically name de middle name node, to be reused in Gatsby, whitout errors from different database name.

### Documentation

**gatsby-node**
```
pluginOptions.name ?? dbName
```

**README**
- **name**: indicates node middle name. ex. mongodbNameDocuments

2021-11-23 16:11 UTC, sandu885 submitted a review, later dismissed

2021-12-17 21:09 UTC, wardpeet requested changes
Thanks for the PR! Can we rename it to typePrefix?

2021-12-17 21:09 UTC, wardpeet commented on packages/gatsby-source-mongodb/README.md
> +- **name**: indicates node middle name. ex. mongodbNameDocuments
```suggestion
- **typePrefix**: the prefix you want to add to your entity types (dbName by default)
```

2021-12-17 21:09 UTC, wardpeet commented on packages/gatsby-source-mongodb/src/gatsby-node.js
> +            pluginOptions.name ?? dbName,
```suggestion
            pluginOptions.typePrefix ?? dbName,
```

2022-03-16 11:53 UTC, wardpeet approved these changes

2022-03-16 11:54 UTC, merged