✏️ Typo: gatbyjs.org -> gatsbyjs.com
gatsbyjs/gatsby pull request #34402
Opened 2022-01-05 07:34 UTC by AnilSeervi

## Description
✏️ Typo: gatbyjs.org -> gatsbyjs.com

### Documentation

## Related Issues

2022-01-05 10:20 UTC, tyhopp commented
Hi @AnilSeervi, thanks for the PR!

It looks like the CI didn't run on your PR, could you push an empty commit or [enable us to make edits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so that we can have it run?

I also had a look at the docs subdir and noticed there were other occurrences of `gatsbyjs.org` (such as [this occurrence](https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/gatsby-style-guide.md?plain=1#L45)) that we can change (ignoring store and example urls like using-gatsby-image). If you're interested, it would be great if you could help also change those.

2022-01-05 17:41 UTC, AnilSeervi commented
> Hi @AnilSeervi, thanks for the PR!
> 
> It looks like the CI didn't run on your PR, could you push an empty commit or [enable us to make edits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so that we can have it run?
> 
> I also had a look at the docs subdir and noticed there were other occurrences of `gatsbyjs.org` (such as [this occurrence](https://github.com/gatsbyjs/gatsby/blob/master/docs/contributing/gatsby-style-guide.md?plain=1#L45)) that we can change (ignoring store and example urls like using-gatsby-image). If you're interested, it would be great if you could help also change those.

I went ahead and fixed all occurences of `gatbsy.org` in _/docs_

Also fixed some 404 links while I was at it ✨

2022-01-06 09:49 UTC, tyhopp approved these changes
Looks great, thanks @AnilSeervi!

2022-01-06 10:02 UTC, tyhopp requested changes
I did find one small thing, could you please use relative links for the case above? Thanks!

2022-01-06 10:02 UTC, tyhopp commented on docs/docs/how-to/styling/using-web-fonts.md
> +You can add Typekit Web Fonts to your project by using the [gatsby-plugin-web-font-loader](https://www.gatsbyjs.com/packages/gatsby-plugin-web-font-loader/?=font) and your [Adobe Fonts project id](ht
```suggestion
You can add Typekit Web Fonts to your project by using the [gatsby-plugin-web-font-loader](/plugins/gatsby-plugin-web-font-loader/?=font) and your [Adobe Fonts project id](https://fonts.adobe.com/my_fonts#web_projects-section). For example, this is how you can add Futura to your project.
```

Links in docs should be relative to make use of `gatsby-link`.

2022-01-07 01:58 UTC, tyhopp approved these changes

2022-01-07 01:59 UTC, merged