fix: usability updates for the info and link indicator buttons
gatsbyjs/gatsby pull request #34562
Opened 2022-01-21 19:38 UTC by leithonenglish

- Fixes build state
- Fixes issue where error and success state show tooltip on hover

2022-01-21 19:42 UTC, pvorozhe approved these changes

2022-01-21 19:59 UTC, TylerBarnes requested changes
It looks good to me but the conventional commit title should include the package name:
`fix(gatsby-plugin-gatsby-cloud):`

2022-01-21 20:30 UTC, TylerBarnes approved these changes

2022-01-24 13:24 UTC, veryspry requested changes

2022-01-24 14:29 UTC, leithonenglish commented on packages/gatsby-plugin-gatsby-cloud/src/components/buttons/InfoIndicatorButton.js
> +    if (buttonProps?.active && buttonProps.onClick) {
Yeah we call track event

2022-01-26 18:49 UTC, veryspry approved these changes
Nice work!

2022-01-26 19:06 UTC, merged