chore(gatsby-plugin-remove-trailing-slashes): add deprecation warnings
gatsbyjs/gatsby pull request #34604
Opened 2022-01-27 08:50 UTC by marvinjude

## Description

### Documentation

## Related Issues

2022-01-27 13:12 UTC, LekoArts requested changes

2022-01-31 09:05 UTC, LekoArts approved these changes

2022-01-31 09:05 UTC, merged

2022-01-31 09:14 UTC, marvinjude commented
@LekoArts I guess we need to release the next minor before taking[ the other PR](jon-sully/gatsby-plugin-force-trailing-slashes#23) out of draft mode

2022-01-31 09:16 UTC, LekoArts commented
Yes