feat(create-gatsby): Add vanilla extract to stying options
gatsbyjs/gatsby pull request #34687
Opened 2022-02-02 13:21 UTC by marvinjude

## Description

### Documentation

## Related Issues

2022-02-02 14:02 UTC, marvinjude commented
Fixing Tests ..

2022-02-03 09:39 UTC, LekoArts requested changes
I'm not a fan of adding a new json file. Let's add it to the existing `styles.json` and instead edit the `makeChoices` function to get an optional third argument with a list of things to filter out.

Then in the `generateQuestions` function you add an optional third arg that is a free form object where you can e.g. add `ts: true`. Then you use that to decide in `generateQuestions` to pass that filter to the `makeChoices`

2022-02-03 09:39 UTC, LekoArts commented on packages/create-gatsby/src/questions/lang-ts-styles.json
> +}
```suggestion
{
  "gatsby-plugin-vanilla-extract": {
    "message": "vanilla-extract",
    "dependencies": [
      "@vanilla-extract/webpack-plugin",
      "@vanilla-extract/css",
      "@vanilla-extract/babel-plugin"
    ]
  }
}
```

Once you move it to the `styles.json` it needs to be in this shape

2022-02-03 14:57 UTC, LekoArts requested changes
![Bildschirmfoto 2022-02-03 um 15 54 45](https://user-images.githubusercontent.com/16143594/152367424-595b8b72-4255-4576-86c5-8a0f469ea032.png)

This changes the order of the entries, which makes e.g. the "Done" step at the features not correct anymore.

I'd say just add it to styles.json and remove everything else

2022-02-03 15:24 UTC, marvinjude commented
> ![Bildschirmfoto 2022-02-03 um 15 54 45](https://user-images.githubusercontent.com/16143594/152367424-595b8b72-4255-4576-86c5-8a0f469ea032.png)
> 
> This changes the order of the entries, which makes e.g. the "Done" step at the features not correct anymore.
> 
> I'd say just add it to styles.json and remove everything else

2022-02-03 15:35 UTC, marvinjude commented
Ah! The order. No worth exploring other workarounds I guess

2022-02-04 11:17 UTC, LekoArts approved these changes

2022-02-04 11:17 UTC, merged