docs(gatsby-source-filesystem): using environment variables to source files
gatsbyjs/gatsby pull request #35056
Opened 2022-03-05 12:04 UTC by baranbbr

## Description

Adds a section to `sourcing-from-filesystem` on how environment variables can be used to source files.
For example, you might do this if you want to source a smaller batch of files when in development, to save on local build times.

If/when these changes get approved, It might be worth also mentioning them here: [gatsbyjs.com/docs/how-to/performance/improving-build-performance/](https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/).

Reference for changes:
- [paulie.dev/posts/2021/07/gatsby-slow-local-build-times/](https://paulie.dev/posts/2021/07/gatsby-slow-local-build-times/) @PaulieScanlon

2022-03-07 09:37 UTC, LekoArts requested changes
Thanks for the PR! I've got a couple of improvements :)

2022-03-07 09:37 UTC, LekoArts commented on docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md
> +## Sourcing Files using Environment Variables
```suggestion
## Conditionally sourcing files using environment variables
```

One is not really "using" environment variables but is using them to conditionally set `path`

2022-03-07 09:37 UTC, LekoArts commented on docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md
> +In the example below in `gatsby-config.js` if the environment variable `NODE_ENV` is set to development, only the content in the specified path will be sourced.
```suggestion
You can conditionally set the `path` option using environment variables. For context, you might decide to do this if you're sourcing a lot of files and you're interested in only sourcing a smaller batch of files during `gatsby develop`. This is also helpful when you e.g. have a staging and production environment (signaled through environment variables).

The example below shows how to use `NODE_ENV` (which is automatically set to `development` during `gatsby develop`) to only source a smaller portion of the content during development. For `gatsby build` the full dataset will be used.
```

Wanted to point out that the key here is to conditionally set the `path` option.

2022-03-07 09:37 UTC, LekoArts commented on docs/docs/how-to/sourcing-data/sourcing-from-the-filesystem.md
> +module.exports = {
```suggestion
module.exports = {
```

The `dotenv` is not necessary as `NODE_ENV` will be set by Gatsby automatically

2022-03-08 01:44 UTC, baranbbr commented
Amazing, thanks for the changes @LekoArts ❤️

Before merging, is it worth mentioning this in the improving build performance section linked above?

2022-03-09 13:14 UTC, baranbbr commented
Done! Hope that's okay and the link to [gatsbyjs.com/docs/how-to/sourcing-from-the-filesystem](https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-the-filesystem/) works 😅

2022-03-10 12:08 UTC, LekoArts approved these changes
Thanks!

2022-03-10 12:08 UTC, merged