feat(gatsby-source-contentful): improve gatsby-plugin-image errors
gatsbyjs/gatsby pull request #35068
Opened 2022-03-07 11:51 UTC by wardpeet

## Description

Show proper error when gatsby-plugin-image is not available or configured.

2022-03-07 11:52 UTC, wardpeet commented on packages/gatsby-source-contentful/src/source-nodes.js
> +  const fetchActivity = reporter.activityTimer(
These edits got removed by rebasing in image-cdn PR

2022-03-07 12:11 UTC, LekoArts requested changes
Two smaller nits

2022-03-07 12:11 UTC, LekoArts commented on packages/gatsby-source-contentful/src/create-schema-customization.js
> +      command = `yarn add gatsby-plugin-image`
I don't think other error messages care about this so I'm leaning a bit towards removing this as our docs stance is also do only ever show npm (as with that you'd then also need to support pnpm etc.)

2022-03-07 12:11 UTC, LekoArts commented on packages/gatsby-source-contentful/src/create-schema-customization.js
> +        sourceMessage: `Gatsby-plugin-image is missing from your project.\n\nPlease install it with: ${command}.`,
```suggestion
        sourceMessage: `gatsby-plugin-image is missing from your project.\n\nPlease install it with: ${command}.`,
```

2022-03-07 12:11 UTC, LekoArts commented on packages/gatsby-source-contentful/src/create-schema-customization.js
> +        sourceMessage: `Gatsby-plugin-image is missing from your gatsby-config file.\n\nPlease add "gatsby-plugin-image" to your plugins array.`,
```suggestion
        sourceMessage: `gatsby-plugin-image is missing from your gatsby-config file.\n\nPlease add "gatsby-plugin-image" to your plugins array.`,
```

2022-03-08 13:52 UTC, axe312ger approved these changes
LGTM! Thanks!

2022-03-09 08:54 UTC, LekoArts approved these changes

2022-03-09 08:54 UTC, merged