fix(gatsby): Throw Typegen errors & other fixes
gatsbyjs/gatsby pull request #35683
Opened 2022-05-17 10:49 UTC by LekoArts

- initial
- write out scalar in ts types
- properly end activity and add structured error

## Description

### Documentation

## Related Issues

2022-05-17 14:02 UTC, aaronadamsCA commented
Oh good, I was just coincidentally checking how you worked around the generic `JSON` scalar type.

Related feature request: #33317

2022-05-17 14:06 UTC, aaronadamsCA commented
Also, if this helps, in our environment the `gatsby-plugin-image#IGatsbyImageData` syntax didn't work. We had to use a dynamic import expression (`import('gatsby-plugin-image').IGatsbyImageData`) instead.

2022-05-17 14:35 UTC, LekoArts commented
> Also, if this helps, in our environment the `gatsby-plugin-image#IGatsbyImageData` syntax didn't work. We had to use a dynamic import expression (`import('gatsby-plugin-image').IGatsbyImageData`) instead.

Works in my testing. It adds

```ts
import type { IGatsbyImageData } from 'gatsby-plugin-image';
```

At the top of the file and then reuses that in the scalars

```ts
type Scalars = {
  GatsbyImageData: IGatsbyImageData;
  JSON: Record<string, unknown>;
};
```

2022-05-18 07:19 UTC, LekoArts commented
Oh, you were right. The global namespace doesn't work if you add an import, so I switched it to the dynamic import.

Luckily this was also caught by the e2e tests 👍

2022-05-18 09:31 UTC, aaronadamsCA commented
@LekoArts That was the only one we had encountered so far.

Looking forward to seeing this ship!

2022-05-18 10:30 UTC, wardpeet commented
Looks good, do you want to do the same for imageCDN located in gatsby-plugin-utils?

2022-05-18 19:25 UTC, wardpeet approved these changes

2022-05-19 06:35 UTC, pieh requested changes

2022-05-19 06:35 UTC, pieh commented on packages/gatsby-plugin-utils/src/polyfill-remote-file/graphql/gatsby-image-resolver.ts
> +    type: `GatsbyImageData!`,
This is a breaking change in sense that it requires users to bump `gatsby` package (to version that actually creates that scalar) (this comment apply to all places that make similar swap)

2022-05-19 08:10 UTC, pieh approved these changes

2022-05-19 08:39 UTC, merged