fix(gatsby-source-wordpress): bug patch for issue 35460
gatsbyjs/gatsby pull request #35817
Opened 2022-06-01 15:02 UTC by tsdexter

## Description

Check the `pluginOptions.type.MediaItem.exclude` before fetching referenced media items during page updates

### Documentation

## Related Issues

Fixes #35460

2022-06-01 15:11 UTC, TylerBarnes requested changes

2022-06-01 15:11 UTC, TylerBarnes commented on packages/gatsby-source-wordpress/src/steps/source-nodes/update-nodes/wp-actions/update.js
> +  if (!pluginOptions.type.MediaItem.exclude) {
```suggestion
  if (!pluginOptions.type?.MediaItem?.exclude) {
```

2022-06-01 16:39 UTC, TylerBarnes approved these changes
Looks good! Thanks for this @tsdexter !

2022-06-01 16:39 UTC, merged

2022-06-02 13:05 UTC, tsdexter commented
@TylerBarnes would it make sense to localize the check into the function? If so, I can do that and cleanup the other individual checks. 

Something like: 

```js
export default async function fetchReferencedMediaItemsAndCreateNodes({
  referencedMediaItemNodeIds,
  mediaItemUrls,
}) {
  const state = store.getState()
  const queryInfo = state.remoteSchema.nodeQueries.mediaItems
  const { helpers, pluginOptions } = state.gatsbyApi

  if (!pluginOptions.type.MediaItem.exclude) return []

  const { createContentDigest, actions } = helpers
  const { url } = pluginOptions
  const { typeInfo, settings, selectionSet, builtFragments } = queryInfo
...
```

2022-06-02 13:26 UTC, TylerBarnes commented
Yeah, that seems reasonable 👍