chore(docs): Add Gatsby Head
gatsbyjs/gatsby pull request #36125
Opened 2022-07-14 07:45 UTC by LekoArts

- initial
- add using-gatsby-head example initial
- write example

## Description

### Documentation

## Related Issues

2022-07-14 12:01 UTC, Khaledgarbaya submitted a review, later dismissed
LGTM

2022-07-14 12:10 UTC, marvinjude requested changes

2022-07-15 07:53 UTC, tyhopp commented on docs/docs/reference/built-in-components/gatsby-head.md
> +Compared to [react-helmet](https://github.com/nfl/react-helmet) or other similar solutions, Gatsby Head is easier to use, more performant, has a smaller bundle size, and is supporting all latest Reac
```suggestion
Compared to [react-helmet](https://github.com/nfl/react-helmet) or other similar solutions, Gatsby Head is easier to use, more performant, has a smaller bundle size, and supports the latest React features.
```

2022-07-15 07:53 UTC, tyhopp commented on docs/docs/reference/built-in-components/gatsby-head.md
> +- If you want to add `<script />` tags to your pages, use the [Gatsby Script Component](/docs/reference/built-in-components/gatsby-script/).
```suggestion
- For most `<script>` tag use cases you should use the [Gatsby Script Component](/docs/reference/built-in-components/gatsby-script/) in your pages or components.
```

2022-07-15 08:15 UTC, tyhopp commented on docs/docs/reference/built-in-components/gatsby-head.md
> +- For most `<script>` tag use cases you should use the [Gatsby Script Component](/docs/reference/built-in-components/gatsby-script/) in your pages or components.
```suggestion
- Data block `<script>` tags such as `<script type="application/ld+json">` can go in the `Head` function, but dynamic scripts are better loaded with the [Gatsby Script Component](/docs/reference/built-in-components/gatsby-script/) in your pages or components.
```

2022-07-15 09:06 UTC, marvinjude submitted a review, later dismissed

2022-07-19 05:49 UTC, tyhopp approved these changes

2022-07-19 07:09 UTC, tyhopp approved these changes

2022-07-19 07:52 UTC, merged