chore(docs): migrate cloud docs to .com
gatsbyjs/gatsby pull request #36389
Opened 2022-08-15 13:16 UTC by MarcusCole518

## Description

This PR is to merge the following docs from our Gatsby Cloud Knowledge Base to the gatsbyjs.com docs.

*Links are to current Cloud Docs*

1. Create a Site from a Template: https://support.gatsbyjs.com/hc/en-us/articles/360059155134-Create-a-Site-from-a-Template
2. Create a Site from a Repository: https://support.gatsbyjs.com/hc/en-us/articles/360059253654-Create-a-Site-from-a-Repository
3. Build and Preview Webhooks: https://support.gatsbyjs.com/hc/en-us/articles/360052324394-Build-and-Preview-Webhooks
4. Deploying to Gatsby Cloud Hosting: https://support.gatsbyjs.com/hc/en-us/articles/360061641114-Deploying-to-Gatsby-Cloud-Hosting
5. Setting a Node.js Version for your Gatsby Cloud Site: https://support.gatsbyjs.com/hc/en-us/articles/360052876333-How-do-I-set-a-Node-js-version-for-my-site-
6. Apex Domains and "www" Subdomains: https://support.gatsbyjs.com/hc/en-us/articles/360061651754-Apex-Domains-and-www-Subdomains
7. Remove Trailing Slash in Netlify URLs: https://support.gatsbyjs.com/hc/en-us/articles/360056349113-Remove-trailing-slash-in-Netlify-URLs
8. Outgoing Notifications: https://support.gatsbyjs.com/hc/en-us/articles/1500000480181-Outgoing-Notifications

2022-08-17 11:15 UTC, LekoArts requested changes
First pass on this, I'd need to dig into the details later

2022-08-17 11:15 UTC, LekoArts commented on docs/docs/reference/cloud/apex-and-subdomains.md
> +All `gatsbyjs.io` domains will 301 redirect to the primary domain that you select.
Explain what a 301 redirect is

2022-08-17 11:15 UTC, LekoArts commented on docs/docs/reference/cloud/build-and-preview-webhooks.md
> +description: "A webhook is an action that runs when the application providing the webhook is notified. The webhook has a URL which can receive HTTP requests (usually POST). A request sent to this URL
That description is too long, needs to be more concise

2022-08-17 11:15 UTC, LekoArts commented on docs/docs/reference/cloud/outgoing-notifications.md
> +title: "Outgoing Notifications"
This is not a reference guide but a how-to guide

2022-08-19 03:11 UTC, MarcusCole518 commented on docs/docs/how-to/cloud/create-site-from-repository.md
> +3. The base directory, i.e., the directory containing the Gatsby site (the root directory, `/`, is default).
thanks for the tip! This worked well on the subsections but didn't seem to work for the h3 steps; each step was still listed as "1"

2022-08-19 09:55 UTC, LekoArts requested changes
Overall it's nearly there. Once the things I mentioned are resolved it would be good to be merged (can also happen in my absence)

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/create-site-from-repository.md
> +In the "Import from a Git repository" section, choose your Git provider and install the Gatsby Cloud app. For the sake of this article you'll use GitHub, however GitLab and Bitbucket are also support
The proper noun for GitHub is `GitHub` and in some other places of the added docs we have `Github`. So make sure that those are all consistent and correct 👍  Same applies to `GitLab` and `BitBucket`

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/create-site-from-repository.md
> +### 1. Select a git provider
```suggestion
### 1. Select a Git provider
```

Maybe also in other places, didn't check :)

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/create-site-from-repository.md
> +![Button to add a site from the Gatsby Cloud dashboard](../../images//add-site.png)
```suggestion
![Button to add a site from the Gatsby Cloud dashboard](../../images/add-site.png)
```

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/outgoing-notifications.md
> +1. First, navigate to Site Settings. In the sidebar menu under "General", select **Outgoing Notifications**. Then click **Add Notification** and choose the Webhooks option.
(This also applies to the other docs)

Similarly to my comment in https://github.com/gatsbyjs/gatsby/pull/36218#discussion_r934198384 we should keep it consistent how we denote buttons/things to click in the UI.

I'd change the sentence to this:

```suggestion
1. First, navigate to "Site Settings". In the sidebar menu under "General", select **"Outgoing Notifications"**. Then click **"Add Notification"** and choose the "Webhooks" option.
```

So use bolding where necessary and use `""` to denote the buttons. This is how it was done in https://github.com/gatsbyjs/gatsby/blob/aeae8f366a48a1ec7832dc61b70b719ec7f92cef/docs/docs/how-to/cloud/adding-a-custom-domain.md after my comments

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/outgoing-notifications.md
> +You can expect the message payload to appear as follows:
```suggestion
You can expect the message payload to appear as following:
```

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/outgoing-notifications.md
> +1. First, visit https://api.slack.com/apps?new_app=1 to add a new Slack app. Add one for a workspace where you have [appropriate permissions](https://slack.com/help/articles/201314026-Permissions-by-
```suggestion
1. First, [add a new Slack app](https://api.slack.com/apps?new_app=1). Add one for a workspace where you have [appropriate permissions](https://slack.com/help/articles/201314026-Permissions-by-role-in-Slack#apps-integrations).
```

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/outgoing-notifications.md
> +4. Finally, return to Gatsby Cloud and navigate to the Outgoing Ntifications settings. Click **Add Notification** and choose the Slack option. Paste the Slack application's webhook URL that you previ
```suggestion
4. Finally, return to Gatsby Cloud and navigate to the "Outgoing Notifications" settings. Click **"Add Notification"** and choose the "Slack" option. Paste the Slack application's webhook URL that you previously copied into the Outgoing Webhook URL field.
```

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/how-to/cloud/set-node-version.md
> +You can set your Node.js version using the `NODE_VERSION` environment variable inside Gatsby Cloud. Read more about setting environment variables [here](../../reference/cloud/managing-environment-var
"Here" is a bad link text: https://www.gatsbyjs.com/contributing/gatsby-style-guide/#use-clear-hyperlinks

```suggestion
You can set your Node.js version using the `NODE_VERSION` environment variable inside Gatsby Cloud. Read more about [setting environment variables](/docs/reference/cloud/managing-environment-variables).
```

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/reference/cloud/apex-and-subdomains.md
> +Adding a custom domain to your Gatsby Cloud site will add both the apex domain and "www" subdomain. This guide will show you how to configure these domains, and redirect between the two.
Add links to explain what an "Apex" domain is

2022-08-19 09:55 UTC, LekoArts commented on docs/docs/reference/cloud/apex-and-subdomains.md
> +3. Follow the directions for adding [DNS records](cloudflare.com/learning/dns/dns-records/) for both of the domains that are listed. The apex domain will need an A record pointed to an IP address and
```suggestion
3. Follow the directions for adding [DNS records](https://cloudflare.com/learning/dns/dns-records/) for both of the domains that are listed. The apex domain will need an A record pointed to an IP address and the subdomain will need a CNAME pointed at your Gatsby Hosting default URL, `YOUR_SITE_PREFIX`.
```

2022-08-26 17:15 UTC, j0sh77 commented on docs/docs/how-to/cloud/create-site-from-repository.md
> +description: "How to create a Gatsby Cloud site from a repository"
Nit-picking: the description format in these docs are not consistent. Can we try to sync them up with "Learn how to..."?

```suggestion
description: "Learn how to create a Gatsby Cloud site from a repository"
```

2022-08-26 17:16 UTC, j0sh77 approved these changes
Looks good minus the nit-pick. Feel free to ignore and ping me when you're ready to merge. 🚀 
Thanks for working through this!

2022-08-26 17:19 UTC, j0sh77 commented on docs/docs/reference/cloud/build-and-preview-webhooks.md
> +description: "This guide outlines the functionality of and differences between Gatsby's Build and Preview webhooks"
```suggestion
description: "Learn about Gatsby's Build and Preview webhooks and their differences"
```

2022-08-29 14:01 UTC, j0sh77 commented on docs/docs/how-to/cloud/create-site-from-template.md
> +description: "How to create a Gatsby Cloud site from a template"
```suggestion
description: "Learn how to create a Gatsby Cloud site from a template"
```

2022-08-29 14:01 UTC, j0sh77 commented on docs/docs/how-to/cloud/deploying-to-gatsby-cloud-hosting.md
> +description: "This tutorial will show you how to deploy your site to Gatsby Cloud hosting."
```suggestion
description: "Learn how to deploy your site to Gatsby Cloud hosting."
```

2022-08-29 14:02 UTC, j0sh77 commented on docs/docs/reference/cloud/apex-and-subdomains.md
> +description: "How to configure your apex and subdomains in Gatsby Cloud"
```suggestion
description: "Learn how to configure your apex and subdomains in Gatsby Cloud"
```

2022-08-29 14:35 UTC, j0sh77 approved these changes

2022-08-29 14:35 UTC, j0sh77 commented
THANK YOU :shipit: 🚀

2022-08-29 14:35 UTC, merged