feat(gatsby): expose loadPageDataSync
gatsbyjs/gatsby pull request #36492
Opened 2022-08-30 11:52 UTC by openscript

According to https://github.com/gatsbyjs/gatsby/discussions/35841#discussioncomment-3357209 there is a `loadPageDataSync` function, which returns the page context to the corresponding `pathname`. So far this was not reflected in the type definitions, what is changed with this PR.

## Description

### Documentation

## Related Issues

2022-09-12 08:02 UTC, LekoArts requested changes

2022-09-12 08:02 UTC, LekoArts commented on packages/gatsby/index.d.ts
> +  loadPageDataSync: (pathname: string) => { result: PageContextType }
The function gets you the page context for the `pathname` you give it, so I don't think we can use the generic `PageContextType` here as it'll be (potentially) different for each page. Current code assumes that `PageContextType` would be the same for each page. So let's do this instead?

```suggestion
  loadPageDataSync: (pathname: string) => { result: Record<string, unknown> }
```

2022-09-12 10:19 UTC, LekoArts approved these changes

2022-09-12 10:21 UTC, merged

2022-09-22 15:20 UTC, openscript commented
@LekoArts Is `loadPageDataSync` really exported to `onRenderBody`? 

When I console logged the first parameter I got:

```
{
  setHeadComponents: [Function: setHeadComponents],
  setHtmlAttributes: [Function: setHtmlAttributes],
  setBodyAttributes: [Function: setBodyAttributes],
  setPreBodyComponents: [Function: setPreBodyComponents],
  setPostBodyComponents: [Function: setPostBodyComponents],
  setBodyProps: [Function: setBodyProps],
  pathname: '/'
}
```

.. and my integration testing shows: `WebpackError: ReferenceError: loadPageDataSync is not defined (from plugin: gatsby-plugin-i18n-l10n)`

Am I understanding something wrong here?