feat(gatsby): support node: protocol when bundling engines
gatsbyjs/gatsby pull request #36506
Opened 2022-08-31 17:59 UTC by pieh

## Description

With introduction of `node:` protocol/imports ( https://nodejs.org/api/esm.html#node-imports ) packages begun to use it and this PR adds bundling support for those. Without it we are getting problems like ones described in https://github.com/webpack/webpack/issues/13290

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/36500

2022-08-31 18:04 UTC, j0sh77 approved these changes
Looks good to me minus the one test change

2022-08-31 18:04 UTC, j0sh77 commented on e2e-tests/production-runtime/cypress/integration/ssr.js
> +  it.only(`engines work when bundled code contains node:path import`, () => {
```suggestion
  it(`engines work when bundled code contains node:path import`, () => {
```

2022-08-31 18:05 UTC, j0sh77 requested changes
lol clicked the wrong button

2022-08-31 18:11 UTC, j0sh77 approved these changes
🔥 :shipit: 🔥

2022-08-31 18:35 UTC, pieh commented
Ugh, the node version we use for e2e in circleci doesn't support `node:` protocol, so build fails even before compiling / validating engines. Will think on how to address that (without just removing the test heh)

2022-09-01 10:31 UTC, pieh commented
I did add hacky polyfill to e2e/prod that allows importing `node:` (we do execute that code during the build so that has to work to test if bundling it works as well), now it should be ready

2022-09-01 11:09 UTC, marvinjude approved these changes

2022-09-01 13:38 UTC, merged