feat(gatsby): Normalize module keys between webpack plugin and loader
gatsbyjs/gatsby pull request #36644
Opened 2022-09-20 09:29 UTC by tyhopp

## Description

Normalize module keys between the partial hydration webpack loader and plugin.

Previously the actual resource path was used, which caused problems because the different modules can be loaded in the loader and plugin based off of what is declared in `package.json`.

### Documentation

N/A

## Related Issues

[sc-55773]

2022-09-21 11:53 UTC, LekoArts commented on packages/gatsby/src/utils/webpack/utils/create-normalized-module-key.ts
> +export function createNormalizedModuleKey(
Talked to @wardpeet - we'll want to keep things _consistent_ so we should  use:

https://github.com/gatsbyjs/gatsby/blob/c073bbea40379adc62bd891da9f65ff2756b120b/packages/gatsby-core-utils/src/path.ts#L80-L94

It just converts everything to forward slash and then use that

2022-09-23 09:50 UTC, LekoArts approved these changes

2022-09-23 12:10 UTC, LekoArts requested changes
Oh, windows tests actually caught something:

```shell
Error: expect(received).toMatchSnapshot()

Snapshot name: `should normalize bare module imports from node_modules 1`

Snapshot: "file://node_modules/package-name"
Received: "file://Users/username/project/node_modules/package-name"
```

2022-09-26 03:37 UTC, tyhopp commented
> Oh, windows tests actually caught something

Fixed in https://github.com/gatsbyjs/gatsby/pull/36644/commits/8f1180278c5e90e4d17f40da1ab3784efa8a6d03

2022-09-26 07:57 UTC, pieh approved these changes
LGTM, had minor NIT but we can just go ahead and merge as-is

2022-09-26 07:57 UTC, pieh commented on packages/gatsby/src/utils/webpack/utils/__tests__/create-normalized-module-key.ts
> +  expect(normalizedModuleKey).toMatchSnapshot()
NIT: I'd suggest using `.toMatchInlineSnapshot()` here given that output is not large, and that will collocate "expected" value to be here, making it easier to see what assertion is actually being done here (regular snapshot requires looking stuff up in `.snap` files etc).

Not big deal, just my preference for this kind of things

2022-09-26 10:04 UTC, merged