chore(docs): Update Head API about `<html>` and `<body>` attributes
gatsbyjs/gatsby pull request #37491
Opened 2023-01-18 16:32 UTC by pieh

## Description

Follow up to https://github.com/gatsbyjs/gatsby/pull/37449 updating docs supporting new feature

### Documentation

## Related Issues

[sc-59890]

2023-01-18 16:46 UTC, pieh commented on docs/docs/reference/built-in-components/gatsby-head.md
> +> Support for the editing `<html>` and `<body>` added in `gatsby@5.5.0`.
Optimistic version - might need to update if feature doesn't land in next minor release

2023-01-19 09:36 UTC, marvinjude commented on docs/docs/reference/built-in-components/gatsby-head.md
> +Gatsby will use provided attributes and inject them into resulting html.
Gatsby will pick up attributes on these tags and inject them into resulting html.

2023-01-19 15:17 UTC, LekoArts requested changes

2023-01-25 07:45 UTC, LekoArts approved these changes

2023-01-25 07:45 UTC, merged