Update gatsby-contentful-plugin README
gatsbyjs/gatsby pull request #38480
Opened 2023-08-25 14:34 UTC by stephan1echung

## Description

Replace references to Gatsby Cloud in the gatsby-contentful-plugin readme

### Documentation

### Tests

## Related Issues

2023-08-25 14:57 UTC, benrobertsonio approved these changes

2023-08-29 16:42 UTC, benrobertsonio requested changes

2023-08-29 20:21 UTC, benrobertsonio approved these changes

2023-08-29 22:08 UTC, nickytonline approved these changes
:shipit:

2023-08-30 13:34 UTC, nickytonline commented
@pieh, I'm less familiar with this codebase. I restarted the failed jobs yesterday and they still fail and also triggered a build. Are these particular checks that are failing flaky?

2023-10-02 15:06 UTC, fk approved these changes
:shipit:

2023-10-03 11:40 UTC, merged