feat: update to ESM compatible version of CTF library
gatsbyjs/gatsby pull request #39178
Opened 2024-12-05 13:10 UTC by axe312ger

2024-12-11 15:53 UTC, serhalp commented
Thanks @axe312ger!

It looks like the tests are failing, e.g.

```
/home/circleci/project/packages/gatsby-source-contentful/src/__tests__/fetch-network-errors.js

  ● fetch-retry › request should fail after to many retries

    expect(received).toEqual(expected) // deep equality

    Expected: StringContaining "Fetching contentful data failed: ERR_BAD_RESPONSE 500 MockedContentfulError"
    Received: "Fetching contentful data failed: ERR_BAD_RESPONSE 500 500 MockedContentfulError Mocked message of Contentful error··
    ---
    Request ID: 123abc·
    Attempts: 3·
    ---
```

2024-12-11 16:01 UTC, axe312ger commented
Yes, thanks. Just on it! :)

2024-12-12 09:56 UTC, axe312ger commented
Had to do [772d895](https://github.com/gatsbyjs/gatsby/pull/39178/commits/772d89506f4a907273a0e67e2faa5d9e4084533d) and [8d93859](https://github.com/gatsbyjs/gatsby/pull/39178/commits/8d93859ddf58203ae8ffcd7939d6fa1860253d88) to make CI happy. Please extract, remove, ignore, merge as you like @Gatsby Team

2024-12-12 10:35 UTC, pieh requested changes

2024-12-12 10:35 UTC, pieh commented on .circleci/config.yml
> +      - image: cypress/browsers:node-18.17.19-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
```suggestion
      - image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
```

Per https://hub.docker.com/r/cypress/browsers/tags?name=node-18

2024-12-12 10:35 UTC, pieh commented on .circleci/config.yml
> +      - image: cypress/browsers:node-18.17.19-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
```suggestion
      - image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
```

same as above

2024-12-12 10:36 UTC, axe312ger commented on .circleci/config.yml
> +      - image: cypress/browsers:node-18.17.19-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
thanks

2024-12-13 09:57 UTC, pieh approved these changes

2024-12-13 09:57 UTC, merged